"""
train_sensor.py
===============
Train SVM and MLP classifiers on normalised sensor delta features.

Data loading uses a session-based split strategy: sessions are grouped by label
and then held-out at the session level (not at the sample level) to prevent
data leakage.  This better reflects deployment conditions, where we want the
model to generalise to unseen subjects and posture styles.

Both models are trained, and the one with higher test accuracy is saved as the
primary sensor model.  All artefacts are saved to MODELS_DIR:
  - sensor_model.pkl    : Best sklearn model (SVM or MLP)
  - sensor_scaler.pkl   : Fitted StandardScaler
  - sensor_metrics.json : Accuracy, F1 macro, confusion matrix, model name

Usage::
    python train_sensor.py

Requires labelled CSVs in DATA_DIR (generated by collect_data.py).
"""

import json
import logging
import pickle
import sys
from pathlib import Path
from typing import Dict, List, Tuple

import numpy as np
import pandas as pd
from sklearn.metrics import accuracy_score, confusion_matrix, f1_score
from sklearn.neural_network import MLPClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s  %(levelname)-8s  %(name)s — %(message)s",
    datefmt="%Y-%m-%d %H:%M:%S",
)
logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------
DATA_DIR   = Path(__file__).parent.parent / "data" / "raw"     # CSV input directory
MODELS_DIR = Path(__file__).parent.parent / "models"           # Model output directory

TEST_SESSION_FRACTION = 0.2   # Fraction of sessions per label to hold out for testing
RANDOM_STATE = 42             # Seed for reproducibility

# SVM hyperparameters
SVM_C      = 10
SVM_KERNEL = "rbf"

# MLP hyperparameters
MLP_HIDDEN   = (64, 32)  # Two hidden layers
MLP_MAX_ITER = 500

# Feature and label configuration
FEATURE_COLS = ["delta_c", "delta_th", "delta_l", "delta_tlj"]
LABEL_MAP    = {"good": 0, "slouch": 1, "forward_head": 2}
INVERSE_LABEL_MAP = {v: k for k, v in LABEL_MAP.items()}


# ---------------------------------------------------------------------------
# Data loading
# ---------------------------------------------------------------------------

def load_sessions(data_dir: Path) -> List[Tuple[pd.DataFrame, str]]:
    """
    Glob all CSVs from data_dir and parse their posture label from the filename.

    Expected filename format: <label>_<session_id>.csv
    The label is the first underscore-delimited segment (e.g., 'good', 'slouch').

    Args:
        data_dir: Directory containing labelled session CSV files.

    Returns:
        List of (DataFrame, label_string) tuples.

    Raises:
        FileNotFoundError: If data_dir does not exist.
        RuntimeError: If no valid CSVs are found.
    """
    if not data_dir.exists():
        raise FileNotFoundError(
            f"Data directory not found: {data_dir}\n"
            "Run collect_data.py first to generate training data."
        )

    csv_files = sorted(data_dir.glob("*.csv"))
    if not csv_files:
        raise RuntimeError(
            f"No CSV files found in {data_dir}. "
            "Run collect_data.py --generate-synthetic to create training data."
        )

    sessions: List[Tuple[pd.DataFrame, str]] = []
    for csv_path in csv_files:
        # Derive label from the filename prefix (before first underscore)
        stem = csv_path.stem
        stem = csv_path.stem
        # Match against known labels (handles multi-word labels like 'forward_head')
        label = None
        for known_label in LABEL_MAP:
            if stem.startswith(known_label + "_") or stem == known_label:
                label = known_label
                break
        if label is None:
            logger.warning(
                "Skipping '%s' — filename prefix '%s' is not a known label.",
                csv_path.name,
                label,
            )
            continue
        try:
            df = pd.read_csv(csv_path)
            if df.empty or not all(col in df.columns for col in FEATURE_COLS):
                logger.warning(
                    "Skipping '%s' — missing required feature columns.", csv_path.name
                )
                continue
            sessions.append((df, label))
            logger.debug("Loaded '%s' (%d rows, label='%s').", csv_path.name, len(df), label)
        except Exception as exc:  # noqa: BLE001
            logger.warning("Failed to load '%s': %s", csv_path.name, exc)

    logger.info("Loaded %d sessions from %s.", len(sessions), data_dir)
    if not sessions:
        raise RuntimeError("No valid sessions could be loaded.")
    return sessions


# ---------------------------------------------------------------------------
# Session-level train/test split
# ---------------------------------------------------------------------------

def session_split(
    sessions: List[Tuple[pd.DataFrame, str]],
    test_fraction: float,
) -> Tuple[List[Tuple[pd.DataFrame, str]], List[Tuple[pd.DataFrame, str]]]:
    """
    Split sessions into train and test sets at the session level (not sample level).

    For each label, at least one session is held out for testing.  The split is
    deterministic based on RANDOM_STATE.

    Args:
        sessions:      List of (DataFrame, label) tuples.
        test_fraction: Fraction of sessions to hold out per label.

    Returns:
        Tuple of (train_sessions, test_sessions), each a list of (DataFrame, label).
    """
    rng = np.random.default_rng(RANDOM_STATE)

    # Group session indices by label
    label_to_indices: Dict[str, List[int]] = {}
    for idx, (_, label) in enumerate(sessions):
        label_to_indices.setdefault(label, []).append(idx)

    train_indices: List[int] = []
    test_indices: List[int] = []

    for label, indices in label_to_indices.items():
        indices_arr = np.array(indices)
        rng.shuffle(indices_arr)  # Shuffle in-place for randomised selection
        n_test = max(1, int(len(indices_arr) * test_fraction))
        test_indices.extend(indices_arr[:n_test].tolist())
        train_indices.extend(indices_arr[n_test:].tolist())
        logger.info(
            "Label '%s': %d train sessions, %d test sessions.",
            label,
            len(indices_arr) - n_test,
            n_test,
        )

    train_sessions = [sessions[i] for i in train_indices]
    test_sessions  = [sessions[i] for i in test_indices]
    return train_sessions, test_sessions


# ---------------------------------------------------------------------------
# Feature / label stacking
# ---------------------------------------------------------------------------

def _stack_sessions(
    sessions: List[Tuple[pd.DataFrame, str]],
) -> Tuple[np.ndarray, np.ndarray]:
    """
    Concatenate all session DataFrames into feature matrix X and label vector y.

    Args:
        sessions: List of (DataFrame, label) tuples.

    Returns:
        Tuple (X, y) where X has shape (N, len(FEATURE_COLS)) and y has shape (N,).
    """
    X_parts = []
    y_parts = []
    for df, label in sessions:
        X_parts.append(df[FEATURE_COLS].values)
        y_parts.append(np.full(len(df), LABEL_MAP[label], dtype=np.int64))
    return np.vstack(X_parts), np.concatenate(y_parts)


# ---------------------------------------------------------------------------
# Training & evaluation
# ---------------------------------------------------------------------------

def train_and_evaluate(
    X_train: np.ndarray,
    y_train: np.ndarray,
    X_test: np.ndarray,
    y_test: np.ndarray,
) -> Dict:
    """
    Train both SVM (RBF) and MLP classifiers and return metrics for the best model.

    "Best" is determined by test accuracy.  Both models are trained and logged.

    Args:
        X_train: Training feature matrix, shape (N_train, 4).
        y_train: Training label vector, shape (N_train,).
        X_test:  Test feature matrix, shape (N_test, 4).
        y_test:  Test label vector, shape (N_test,).

    Returns:
        Dict with keys: 'accuracy', 'f1_macro', 'confusion_matrix',
        'model_name', 'model' (the fitted sklearn estimator).
    """
    results = {}

    # --- SVM ---
    logger.info("Training SVM (C=%s, kernel=%s) …", SVM_C, SVM_KERNEL)
    svm = SVC(C=SVM_C, kernel=SVM_KERNEL, probability=True, random_state=RANDOM_STATE)
    svm.fit(X_train, y_train)
    y_pred_svm = svm.predict(X_test)
    acc_svm = accuracy_score(y_test, y_pred_svm)
    f1_svm  = f1_score(y_test, y_pred_svm, average="macro", zero_division=0)
    logger.info("SVM — accuracy=%.4f  F1_macro=%.4f", acc_svm, f1_svm)
    results["svm"] = {"model": svm, "accuracy": acc_svm, "f1_macro": f1_svm,
                       "y_pred": y_pred_svm, "model_name": "SVM"}

    # --- MLP ---
    logger.info("Training MLP (hidden=%s, max_iter=%d) …", MLP_HIDDEN, MLP_MAX_ITER)
    mlp = MLPClassifier(
        hidden_layer_sizes=MLP_HIDDEN,
        max_iter=MLP_MAX_ITER,
        random_state=RANDOM_STATE,
        early_stopping=True,
        validation_fraction=0.1,
    )
    mlp.fit(X_train, y_train)
    y_pred_mlp = mlp.predict(X_test)
    acc_mlp = accuracy_score(y_test, y_pred_mlp)
    f1_mlp  = f1_score(y_test, y_pred_mlp, average="macro", zero_division=0)
    logger.info("MLP — accuracy=%.4f  F1_macro=%.4f", acc_mlp, f1_mlp)
    results["mlp"] = {"model": mlp, "accuracy": acc_mlp, "f1_macro": f1_mlp,
                       "y_pred": y_pred_mlp, "model_name": "MLP"}

    # --- Pick best by test accuracy ---
    best_key = max(results, key=lambda k: results[k]["accuracy"])
    best = results[best_key]
    cm = confusion_matrix(y_test, best["y_pred"]).tolist()

    logger.info(
        "Best model: %s (accuracy=%.4f, F1=%.4f)",
        best["model_name"], best["accuracy"], best["f1_macro"],
    )

    return {
        "accuracy":         best["accuracy"],
        "f1_macro":         best["f1_macro"],
        "confusion_matrix": cm,
        "model_name":       best["model_name"],
        "model":            best["model"],
    }


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> Dict:
    """
    Orchestrate the full training pipeline and persist all artefacts.

    Steps:
      1. Load and session-split all labelled CSVs.
      2. Stack features and labels.
      3. Fit StandardScaler on training data.
      4. Train SVM and MLP; select best.
      5. Save scaler, model, and metrics to MODELS_DIR.

    Returns:
        Metrics dict with 'accuracy', 'f1_macro', 'confusion_matrix', 'model_name'.
    """
    logger.info("=== Sensor Model Training ===")

    # --- Load data ---
    try:
        sessions = load_sessions(DATA_DIR)
    except (FileNotFoundError, RuntimeError) as exc:
        logger.error("%s", exc)
        sys.exit(1)

    # --- Session-level split ---
    train_sessions, test_sessions = session_split(sessions, TEST_SESSION_FRACTION)
    if not train_sessions or not test_sessions:
        logger.error("Not enough sessions for a valid train/test split.")
        sys.exit(1)

    # --- Stack features ---
    X_train, y_train = _stack_sessions(train_sessions)
    X_test,  y_test  = _stack_sessions(test_sessions)
    logger.info(
        "Training samples: %d | Test samples: %d", len(X_train), len(X_test)
    )

    # --- Feature scaling (fit on train only to prevent leakage) ---
    scaler = StandardScaler()
    X_train_scaled = scaler.fit_transform(X_train)
    X_test_scaled  = scaler.transform(X_test)

    # --- Train and evaluate ---
    metrics = train_and_evaluate(X_train_scaled, y_train, X_test_scaled, y_test)

    # --- Persist artefacts ---
    MODELS_DIR.mkdir(parents=True, exist_ok=True)

    # Save scaler
    scaler_path = MODELS_DIR / "sensor_scaler.pkl"
    try:
        with open(scaler_path, "wb") as fh:
            pickle.dump(scaler, fh)
        logger.info("Scaler saved to %s", scaler_path)
    except OSError as exc:
        logger.error("Failed to save scaler: %s", exc)

    # Save best model
    model_path = MODELS_DIR / "sensor_model.pkl"
    try:
        with open(model_path, "wb") as fh:
            pickle.dump(metrics["model"], fh)
        logger.info("Model (%s) saved to %s", metrics["model_name"], model_path)
    except OSError as exc:
        logger.error("Failed to save model: %s", exc)

    # Save metrics (without the non-serialisable 'model' key)
    serialisable_metrics = {k: v for k, v in metrics.items() if k != "model"}
    metrics_path = MODELS_DIR / "sensor_metrics.json"
    try:
        with open(metrics_path, "w", encoding="utf-8") as fh:
            json.dump(serialisable_metrics, fh, indent=2)
        logger.info("Metrics saved to %s", metrics_path)
    except OSError as exc:
        logger.error("Failed to save metrics: %s", exc)

    # --- Print summary ---
    cm_arr = np.array(metrics["confusion_matrix"])
    label_names = list(LABEL_MAP.keys())
    print("\n" + "=" * 60)
    print(f"  Best model       : {metrics['model_name']}")
    print(f"  Test accuracy    : {metrics['accuracy']:.4f}")
    print(f"  Test F1 (macro)  : {metrics['f1_macro']:.4f}")
    print("\n  Confusion matrix:")
    header = "       " + "  ".join(f"{n:>12}" for n in label_names)
    print(header)
    for i, row in enumerate(cm_arr):
        row_str = "  ".join(f"{v:12d}" for v in row)
        print(f"  {label_names[i]:>6}  {row_str}")
    print("=" * 60)

    return serialisable_metrics


if __name__ == "__main__":
    main()
